version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.4

workflows:
  lint-pack_validate_publish-dev:
    jobs:
      # lint the destructured orb YAML files
      - orb-tools/lint

      - orb-tools/pack:
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          context: orb-publishing
          orb-name: circleci/windows
          publish-alpha-version: false
          requires:
            - orb-tools/pack
