blank_issues_enabled: false
contact_links:
  - name: CircleCI Customer Support
    url: https://support.circleci.com/hc/en-us
    about: For CircleCI Windows image issues, please open a support request